language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  # - pip install -r requirements.txt
  
# command to run tests
script:
# Continuous Integration
  # Automated Tests (unit, integration, etc)
  - python -m unittest

  # Build Application
  - docker build .

